import { useEffect, useState } from "react";
import { defaultChatSettings, getBackendSettings, getChatSettings, getInstalledModels, saveChatSettings } from "../../services/api";
import type { BackendSettings, ChatSettings, InstalledModel } from "../../services/api";

function sizeLabel(size?: number) { return size ? `${(size / 1024 ** 3).toFixed(1)} GB` : "Size unavailable"; }

export default function Models() {
  const [status, setStatus] = useState<BackendSettings | null>(null); const [models, setModels] = useState<InstalledModel[]>([]); const [settings, setSettings] = useState<ChatSettings>(getChatSettings()); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); try { const [nextStatus, catalog] = await Promise.all([getBackendSettings(), getInstalledModels()]); setStatus(nextStatus); setModels(catalog.models); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load model information."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const update = (next: ChatSettings) => { setSettings(next); saveChatSettings(next); };
  const custom = settings.temperature !== defaultChatSettings.temperature || settings.maxTokens !== defaultChatSettings.maxTokens || settings.contextMessageLimit !== defaultChatSettings.contextMessageLimit || settings.streaming !== defaultChatSettings.streaming;
  return <div className="page"><h1>Models</h1><button type="button" onClick={() => void load()} disabled={loading}>Refresh models</button>{loading && <p>Loading Ollama model information...</p>}{error && <p className="chat-error">{error}</p>}{status && <section className="model-status"><p><strong>Provider:</strong> {status.ai_provider}</p><p><strong>Active model:</strong> {status.ollama_model}</p><p><strong>Ollama:</strong> {status.provider_available ? "Connected" : "Unavailable"}</p><p>{status.detail}</p><small>Persistent model changes require backend environment configuration and restart.</small></section>}<section className="model-catalog"><h2>Installed Ollama models</h2>{!loading && !models.length && <p>No local models are installed.</p>}{models.map((model) => <div className="model-row" key={model.name}><strong>{model.name}</strong>{model.active && <span>Active</span>}<small>{sizeLabel(model.size)}{model.modified_at ? ` · ${model.modified_at}` : ""}</small></div>)}</section><section className="model-controls"><h2>Generation controls {custom && <small>Custom settings active</small>}</h2><label>Temperature <input type="number" min="0" max="2" step="0.1" value={settings.temperature} onChange={(e) => update({ ...settings, temperature: Math.min(2, Math.max(0, Number(e.target.value))) })} /></label><label>Maximum output tokens <input type="number" min="1" max="4096" value={settings.maxTokens} onChange={(e) => update({ ...settings, maxTokens: Math.min(4096, Math.max(1, Number(e.target.value))) })} /></label><label>Context message limit <input type="number" min="1" max="100" value={settings.contextMessageLimit} onChange={(e) => update({ ...settings, contextMessageLimit: Math.min(100, Math.max(1, Number(e.target.value))) })} /></label><label><input type="checkbox" checked={settings.streaming} onChange={(e) => update({ ...settings, streaming: e.target.checked })} /> Stream responses</label><button type="button" onClick={() => update(defaultChatSettings)}>Reset generation settings</button></section></div>;
}
